### ISSUE TITLE
Error running on Colab

### ISSUE THREAD

**Issue by nobel861017** [chenyaofo/pytorch-cifar-models#6]
Hi, I ran
```
!python -m entry.run --conf conf/cifar10.conf -o output/cifar10/resnet20 -M model.name=cifar10_resnet20
```
on colab, and it gives me the error
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/image-classification-codebase/entry/run.py", line 6, in <module>
    main(get_args())
  File "/content/image-classification-codebase/codebase/main.py", line 234, in main
    main_worker(local_rank, ngpus_per_node, args, args.conf)
  File "/content/image-classification-codebase/codebase/main.py", line 203, in main_worker
    prepare_for_training(conf, args.output_dir, local_rank)
  File "/content/image-classification-codebase/codebase/main.py", line 142, in prepare_for_training
    basic_bs = optimizer_config.pop("basic_bs")
  File "/usr/local/lib/python3.7/dist-packages/pyhocon/config_tree.py", line 274, in pop
    value = self.get(key, UndefinedKey)
  File "/usr/local/lib/python3.7/dist-packages/pyhocon/config_tree.py", line 236, in get
    return self._get(ConfigTree.parse_key(key), 0, default)
  File "/usr/local/lib/python3.7/dist-packages/pyhocon/config_tree.py", line 177, in _get
    u"No configuration setting found for key {key}".format(key='.'.join(key_path[:key_index + 1])))
pyhocon.exceptions.ConfigMissingException: 'No configuration setting found for key basic_bs'
```
Does anyone know how to solve this?

**Comment by chenyaofo** [comment]
Thanks for your feedbacks. I have fixed this.
